# Generated by Django 6.0 on 2025-12-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_about_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.CharField(max_length=500),
        ),
    ]
